name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    # リポジトリをチェックアウトするステップ
    - name: Checkout repository
      uses: actions/checkout@v2

    # Pythonをセットアップするステップ
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # 依存関係をインストールするステップ
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # テストを実行するステップ
    - name: Run tests
      run: |
        python -m unittest discover

    # Python embeddedをダウンロードして解凍するステップ
    - name: Download and extract Python embedded
      run: |
        curl -o python-embedded.zip -L https://www.python.org/ftp/python/3.10.11/python-3.10.11-embed-amd64.zip
        Expand-Archive -Path python-embedded.zip -DestinationPath python-embedded

    # リリース用のzipファイルを作成するステップ
    - name: Create release zip
      run: |
        mkdir release
        xcopy /E /I python-embedded\* release\
        xcopy /E /I * release\
        Compress-Archive -Path release\* -DestinationPath outlook_assistant_release.zip

    # アーティファクトとしてzipファイルをアップロードするステップ
    - name: Upload release artifact
      uses: actions/upload-artifact@v2
      with:
        name: outlook_assistant_release
        path: outlook_assistant_release.zip
